# Generated by Django 3.2.5 on 2021-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
